language: python

python:
  - "3.4"

env:
  global:
  - secure: "LlUvTKYutgxTzaLEfGRws8RBT3xh7qAG+CLEFdy7DR0EC2J/D8rlwP3fnoW267u6v3dCWey0iJ/ZlGH/Bk1lJ6jnp6vAjGBYGdIGzESjtYY0qvRWypimOeCc5y8Uw5d6qY8OdLcSS4+egExVDMLm6g18BPZKrd77kPSSlqY6krE="

branches:
  only:
    - site

cache: apt
sudo: false
addons:
    apt:
      packages:
        - language-pack-es-base

before_install:
  - "pip install --upgrade pip wheel"

install:
    - pip install --upgrade "Nikola[extras]"
    - git config --global user.email carlosvin@gmail.com
    - git config --global user.name carlosvin

script:
    - nikola github_deploy
